
@url= http://localhost:8080/api/v1



################################ People Management ########################################
### Get all people (admin only)
### GET http://localhost:8080/api/v1/people
GET {{url}}/people
Authorization: Basic admin goodpass

### Get people by id (admin only)
### GET http://localhost:8080/api/v1/people/{id}
GET {{url}}/people/3
Authorization: Basic admin goodpass

### Delete people by id (admin only)
### DELETE http://localhost:8080/api/v1/people/{id}
DELETE {{url}}/people/3
Authorization: Basic admin goodpass

### Add people (admin only)
### POST http://localhost:8080/api/v1/people
POST {{url}}/people
Content-Type: application/json
Authorization: Basic admin goodpass

{
    "firstName": "user4",
    "lastName": "tan",
    "emailId": "masonstein@asd.com",
    "birthDate": "1978-10-16",
    "condition": "MODERATE",
    "username": "user4",
    "password": "goodpass",
    "authorities": "ROLE_PATIENT"
}

### Add people (admin only) 2nd guy
### POST http://localhost:8080/api/v1/people

POST {{url}}/people
Content-Type: application/json
Authorization: Basic admin goodpass

{
    "firstName": "Jack",
    "lastName": "Old",
    "emailId": "masonstein@asd.com",
    "birthDate": "1978-10-16",
    "condition": "SEVERE",
    "username": "user3",
    "password": "goodpassw1",
    "authorities": "ROLE_PATIENT"
}

### Update people by id (admin only)
### PUT http://localhost:8080/api/v1/people/{id}
PUT {{url}}/people/2
Content-Type: application/json
Authorization: Basic admin goodpass

{
    "firstName": "firstName",
    "lastName": "lastName",
    "emailId": "emailId@asd.com",
    "birthDate": "2003-10-16",
    "condition": "SEVERE",
    "username": "username12",
    "password": "password",
    "authorities": "ROLE_ADMIN"
}
// Should create another request to update password and authorities, 
//username cannot be change
    
################################## Patient login/registration ########################################

### login (patient only)
### GET http://localhost:8080/api/v1/login/{username}

GET {{url}}/login/admin
Authorization: Basic admin goodpass

### login (admin only)
### GET http://localhost:8080/api/v1/admin/login/{username}

GET {{url}}/admin/login/admin
Authorization: Basic admin goodpass

### Add people (patient only)

POST {{url}}/patient/registration
Content-Type: application/json

{
    "firstName": "Jackson",
    "lastName": "Sim",
    "emailId": "emailId@asd.com",
    "birthDate": "1999-02-15",
    "condition": "MODERATE",
    "username": "jacksonim",
    "password": "password"
}

################################## Kiosk login ########################################
### login (patient only) (Not Working)
### GET http://localhost:8080/api/v1/login/{NRIC}

GET {{url}}/login/T1234567A


################################## Qticket ########################################
### Get Latest Qticket by patient id (Patient /or admin) 
### GET http://localhost:8080/api/v1/patients/{id}/getQ
GET {{url}}/patients/2/getQ
Authorization: Basic admin goodpass

### Get all QTickets (admin only)
### GET http://localhost:8080/api/v1/getAllQ
GET {{url}}/getAllQ
Authorization: Basic admin goodpass

### Get Latest Qticket for today by patient id (Patient /or admin) 
### GET http://localhost:8080/api/v1/patients/{id}/getQtoday
GET {{url}}/patients/2/getQtoday
Authorization: Basic admin goodpass


################################## WalkIn ########################################

### Get new QTicket no with patientId (Patient /or admin)
### (get patient id when during login.)
### POST http://localhost:8080/api/v1/patients/{id}/getnewQ
POST {{url}}/patients/2/getnewQ
Authorization: Basic user2 goodpass
Content-Type: application/json

{

}

### Get waiting List status
### GET http://localhost:8080/api/v1/getWaitingListStatus
GET {{url}}/getWaitingQStatus


################################## Appointment ########################################

### Book new appointment by patientid and datetimeslotid, must be within 3 days from today
### POST 
### {{url}}/appointment/bookNewAppointment/{patientId}/{dateTimeSlotId}
POST {{url}}/appointment/bookNewAppointment/3/2498
Authorization: Basic user2 goodpass
Content-Type: application/json

{
    
}

### Query all available TimeSlot by date
### GET http://localhost:8080/api/v1/appointment/queryAvailableTimeSlot/{date}
GET {{url}}/appointment/queryAvailableTimeSlot/2023-11-04
Authorization: Basic admin goodpass

################################## Payment ########################################

### set ticket to be awaiting payment (admin only)
### PUT http://localhost:8080/api/v1/patient/{id}/setAwaitingPayment/{ticketno}
PUT {{url}}/patient/4/hasSeenDoctor/5
Authorization: Basic admin goodpass
Content-Type: application/json

{

}

### Confirm payment (Patient /or admin)
### PUT http://localhost:8080/api/v1/patient/{personid}/confirmPayment/{ticketno}
PUT {{url}}/patient/3/confirmPayment/1
Authorization: Basic admin goodpass
Content-Type: application/json
{

}

### Get all QTickets awaiting for payment by patient id (Patient /or admin)
### GET http://localhost:8080/api/v1/patient/{personid}/getAwaitingPayment
GET {{url}}/patient/3/getAwaitingPayment
Authorization: Basic admin goodpass

################################## Room ########################################

### Get all rooms
### GET http://localhost:8080/api/v1/rooms
GET {{url}}/rooms
Authorization: Basic admin goodpass

### add room
### POST http://localhost:8080/api/v1/rooms
POST {{url}}/rooms
Authorization: Basic admin goodpass
Content-Type: application/json

{

}

################################## DateTimeSlot ########################################

### Get all DateTimeSlot 
GET {{url}}/datetimeslot
Authorization: Basic admin goodpass

###########################################################

#################################### SCAPPED ########################################
# ################################## Patient ########################################

# ### Get all patients
# GET http://localhost:8080/api/v2/patients

# ### Save patient
# POST http://localhost:8080/api/v2/patients
# Content-Type: application/json

# {
#     "firstName": "Mark",
#     "lastName": "lastName",
#     "emailId": "email",
#     "age": "1",
#     "condition": ["state.condition"]
# }

# ### Update Patient by id
# PUT http://localhost:8080/api/v2/patients/7
# Content-Type: application/json

# {
#     "firstName": "ChangedFirsasedtname",
#     "lastName": "lastName",
#     "emailId": "email",
#     "age": "1",
#     "condition": ["state.condition"]
# }