### 1 ## Get all people
GET http://localhost:8080/api/v1/people
Authorization: Basic admin goodpass

### Get p where id 3
GET http://localhost:8080/api/v1/people/1

### 2 ## Delete p where id 2
DELETE http://localhost:8080/api/v1/people/1
Authorization: Basic admin goodpass

### 3 ## Add people
POST http://localhost:8080/api/v1/people
Content-Type: application/json
Authorization: Basic admin goodpass111
# password: should be at least 8 to 10 characters

{
    "firstName": "zoo",
    "lastName": "king",
    "condition": "critical",
    "age": "40",
    "emailId": "zoo@ab.xy",
    "username": "user1",
    "password": "goodpass", 
    "authorities": "ROLE_USER"
}

### 4 ## Update p where id 1
PUT http://localhost:8080/api/v1/people/1
Content-Type: application/json
Authorization: Basic admin goodpass
# password: should be at least 8 to 10 characters

{
    "firstName": "lion",
    "lastName": "queen",
    "condition": "mild",
    "age": "20",
    "emailId": "zoo@xxx.yy",
    "username": "user1",
    "password": "goodpass", 
    "authorities": "ROLE_ADMIN"
}

###########################################################